# Generated by Django 6.0.3 on 2026-03-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_status'),
        ('marketplace', '0002_product_image'),
    ]

    operations = [
    ]
